### ISSUE TITLE
Stabiliserad uppkoppling till te-servern

### ISSUE THREAD

**Issue by mtorstensson** [JensCarlberg/TeaTimer#6]
Se till att appen inte hänger sig om uppkopplingen till servern strular

**Comment by JensCarlberg** [comment]
Nu när jag tittar i koden ser jag att kommunikationen mellan app och server sker i en egen tråd (MainActivity.addToServer(Tea tea) ansvarar för det), så appen hänger sig no inte om det strular. Det loggas också om den misslyckas .
